// Auto-generated by deploy.sh — 2026-02-12T10:10:22Z
// Network: testnet
// Deployer: 0x9c19049d269c7e153b458d9b9ac9f2c5209243836967ab16fc3b2e01f7ba0dc1

export const packages = {
  entity: "0x5027c19c807223b4b91e8f70b694c5b37118d5ea727d982820b837b54697d7f4",
  components: "0x56056e084dec3522b3b069577bf1409a0927778401ce5534bfe2efba48eae3b4",
  systems: "0x63c83d51f8bd8e07e165df2beab847ac8d5d19f28bc58bbdc6fc47172648f204",
  world: "0xaa168c61e541e29f3ba20fe13c5a27f13fb8858fb11373167012e132fbc64401",
} as const;

export const network = "testnet";
export const deployer = "0x9c19049d269c7e153b458d9b9ac9f2c5209243836967ab16fc3b2e01f7ba0dc1";
