// Auto-generated by upgrade.sh — 2026-02-19T16:10:45Z
// Network: testnet
// Deployer: 0x9c19049d269c7e153b458d9b9ac9f2c5209243836967ab16fc3b2e01f7ba0dc1

export const packages = {
  entity: "0x25013b1c4a8f9cc312c00f89a42cae11db3176db711e352f31e5320a5c96c0a7",
  components: "0x5ada3aeae7fe8aa01c211a7ddd3c05858dcb1800d4f0fc4729ed9b4fe53c5d0a",
  systems: "0x1ff713888ce30165692c3b386a2cf08d6263c0e93bc5c4fd3f06a0c43b239d19",
  world: "0xc1caa6ed11b26124821c56663d904b97ee3faa2d61a90d8773c2be9c367839b2",
} as const;

export const network = "testnet";
export const deployer = "0x9c19049d269c7e153b458d9b9ac9f2c5209243836967ab16fc3b2e01f7ba0dc1";
